services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - media_data:/app/data/media
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.base
      - SECRET_KEY=change-this-to-a-random-secret-key-in-production
      - ALLOWED_HOSTS=*
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_NAME=babybuddy
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432
      - CSRF_TRUSTED_ORIGINS=http://localhost:8080
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: babybuddy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx-docker.conf:/etc/nginx/nginx.conf:ro
      - .:/app:ro
      - media_data:/app/data/media:ro
    depends_on:
      - web

volumes:
  media_data:


# 7:22 pm left breast
